version: '3.7'

services:
  web:
    build: ./
    container_name: "wyz-validator"
    command: "/golang-validation"
    ports:
      - "3001:3001"
    environment:
      GO_ENV: "production"
    volumes:
      - ./:/golang-validation